version: "3"
services:
  node-app:
    image: albek94/my-sio:v1.0.0
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=production
    command: npm start
    env_file:
      - ./.env

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

